/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DriverUsuario;
import com.mycompany.proyecto_sistema_recomendaciones.Perro;
import com.mycompany.proyecto_sistema_recomendaciones.Usuario;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author viankacastro
 */
public class CrearCuenta extends javax.swing.JFrame {

     /**
     * Creates new form CrearCuenta
     */
    private DriverUsuario driver;

    public CrearCuenta(DriverUsuario driver) {
        this.driver = driver;
        initComponents();
        limpiar();
    }
    
    private void limpiar() {
        txtNombreUsuario.setText("");
        txtCorreo.setText("");
        txtPassword.setText("");
    }
    
  private void crearCuenta() {
        String nombre = txtNombreUsuario.getText().trim();
        String correo = txtCorreo.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        if (driver == null) {
            JOptionPane.showMessageDialog(this, "Error de inicialización del controlador.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nombre.isEmpty() || correo.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        driver.validarUsuario("Creada", 0, nombre, correo, password, true);
        System.out.println("SE LOGRO GUARDAR AL USUARIO");
    }

   private void abrirLogin() {
        this.dispose();
        Login login = new Login(driver);
        login.setVisible(true);
    }
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGtamanio = new javax.swing.ButtonGroup();
        BGcolor = new javax.swing.ButtonGroup();
        BGPelo = new javax.swing.ButtonGroup();
        BGpersonalidad = new javax.swing.ButtonGroup();
        BGtoleranciaClima = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        opcion3JL = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnRegresar = new javax.swing.JButton();
        btnRegistrate = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        fondoJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        opcion3JL.setBackground(new java.awt.Color(204, 153, 255));
        opcion3JL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/perrito3.png")
        );
        getContentPane().add(opcion3JL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 250, 290));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 210, 30));

        txtPassword.setText("jPasswordField1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 210, 30));

        btnRegresar.setBackground(new java.awt.Color(228, 176, 139));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(88, 45, 35));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 740, 192, 35));

        btnRegistrate.setBackground(new java.awt.Color(228, 176, 139));
        btnRegistrate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrate.setForeground(new java.awt.Color(88, 45, 35));
        btnRegistrate.setText("Regístrate");
        btnRegistrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrateActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 240, 40));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 210, 30));

        fondoJL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/CrearCuenta.png")
        );
        getContentPane().add(fondoJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1020, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        //iniciarSesion();
         abrirLogin();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrateActionPerformed
        // TODO add your handling code here:
        crearCuenta();
        abrirLogin();
    }//GEN-LAST:event_btnRegistrateActionPerformed

       // Método main para prueba
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new CrearCuenta(new DriverUsuario()).setVisible(true); // Asegúrate de tener un constructor adecuado en DriverUsuario
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGPelo;
    private javax.swing.ButtonGroup BGcolor;
    private javax.swing.ButtonGroup BGpersonalidad;
    private javax.swing.ButtonGroup BGtamanio;
    private javax.swing.ButtonGroup BGtoleranciaClima;
    private javax.swing.JButton btnRegistrate;
    private javax.swing.JButton btnRegresar;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel fondoJL;
    private javax.swing.JLabel opcion3JL;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
