/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DriverUsuario;
import com.mycompany.proyecto_sistema_recomendaciones.Perro;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.util.logging.Logger;


/**
 *
 * @author viankacastro
 */
public class Cuenta extends javax.swing.JFrame {

     /**
     * Creates new form Login
     */
    private DriverUsuario driver;

    public Cuenta(DriverUsuario driver) {
        this.driver = driver;
        initComponents();
    }

   

       private void abrirLogin() {
        this.dispose();
        Login login = new Login(driver);
        login.setVisible(true);
    }
    
     
        
          /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        DriverUsuario driver2 = new DriverUsuario();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuenta(driver2).setVisible(true);

            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGtamanio = new javax.swing.ButtonGroup();
        BGcolor = new javax.swing.ButtonGroup();
        BGPelo = new javax.swing.ButtonGroup();
        BGpersonalidad = new javax.swing.ButtonGroup();
        BGtoleranciaClima = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        btnCerrarSesion = new javax.swing.JButton();
        btnPerrosAdoptados = new javax.swing.JButton();
        btnAdoptarPerro1 = new javax.swing.JButton();
        fondoJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(228, 176, 139));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(88, 45, 35));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 230, 60));

        btnPerrosAdoptados.setBackground(new java.awt.Color(228, 176, 139));
        btnPerrosAdoptados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerrosAdoptados.setForeground(new java.awt.Color(88, 45, 35));
        btnPerrosAdoptados.setText("Perros Adoptados");
        btnPerrosAdoptados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerrosAdoptadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerrosAdoptados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 230, 60));

        btnAdoptarPerro1.setBackground(new java.awt.Color(228, 176, 139));
        btnAdoptarPerro1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdoptarPerro1.setForeground(new java.awt.Color(88, 45, 35));
        btnAdoptarPerro1.setText("Adoptar Perro");
        btnAdoptarPerro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptarPerro1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdoptarPerro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 230, 60));

        fondoJL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/Cuenta.png")
        );
        getContentPane().add(fondoJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        abrirLogin();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPerrosAdoptadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerrosAdoptadosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPerrosAdoptadosActionPerformed

    private void btnAdoptarPerro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptarPerro1ActionPerformed
        // TODO add your handling code here:
        Principal prin = new Principal();
        prin.setVisible(true);
    }//GEN-LAST:event_btnAdoptarPerro1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGPelo;
    private javax.swing.ButtonGroup BGcolor;
    private javax.swing.ButtonGroup BGpersonalidad;
    private javax.swing.ButtonGroup BGtamanio;
    private javax.swing.ButtonGroup BGtoleranciaClima;
    private javax.swing.JButton btnAdoptarPerro1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPerrosAdoptados;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel fondoJL;
    // End of variables declaration//GEN-END:variables
}
