/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DriverUsuario;
import com.mycompany.proyecto_sistema_recomendaciones.Perro;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.util.logging.Logger;


/**
 *
 * @author viankacastro
 */
public class Login extends javax.swing.JFrame {

     /**
     * Creates new form Login
     */
    private DriverUsuario driver;

    public Login(DriverUsuario driver) {
        this.driver = driver;
        initComponents();
        limpiar();
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void limpiar() {
        txtNombreUsuario.setText("");
        txtPassword.setText("");
        //cbRecordarPass.setSelected(false);
    }
    
     private void iniciarSesion() {
        // boolean flag = true; //esto es temporal
        boolean flag = driver.iniciarSesion(txtNombreUsuario.getText(), txtPassword.getText());

        // CrearCuenta crearCuenta = new CrearCuenta(driver); //esto es temporal
        // crearCuenta.crearCuenta2(); //esto es temporal
        if (flag) {
            this.dispose();
            Cuenta cuen = new Cuenta(driver);
            cuen.setVisible(true);
        }
     }
     
        private void abrirCrearCuenta() {
        this.dispose();
        CrearCuenta crearCuenta = new CrearCuenta(driver);
        crearCuenta.setVisible(true);
        }
        
          /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        DriverUsuario driver2 = new DriverUsuario();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(driver2).setVisible(true);

            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGtamanio = new javax.swing.ButtonGroup();
        BGcolor = new javax.swing.ButtonGroup();
        BGPelo = new javax.swing.ButtonGroup();
        BGpersonalidad = new javax.swing.ButtonGroup();
        BGtoleranciaClima = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        opcion3JL = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lbRegistrarse = new javax.swing.JLabel();
        fondoJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        opcion3JL.setBackground(new java.awt.Color(204, 153, 255));
        opcion3JL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/perrito3.png")
        );
        getContentPane().add(opcion3JL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 250, 290));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 200, 30));

        txtPassword.setText("jPasswordField1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 478, 190, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(228, 176, 139));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(88, 45, 35));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 192, 35));

        lbRegistrarse.setText("¿No tienes una cuenta? Registrate");
        lbRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(lbRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 220, -1));

        fondoJL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/Login.png")
        );
        getContentPane().add(fondoJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
       iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void lbRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegistrarseMouseClicked
        // TODO add your handling code here:}
        this.dispose();
        abrirCrearCuenta();
    }//GEN-LAST:event_lbRegistrarseMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGPelo;
    private javax.swing.ButtonGroup BGcolor;
    private javax.swing.ButtonGroup BGpersonalidad;
    private javax.swing.ButtonGroup BGtamanio;
    private javax.swing.ButtonGroup BGtoleranciaClima;
    private javax.swing.JButton btnIniciarSesion;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel fondoJL;
    private javax.swing.JLabel lbRegistrarse;
    private javax.swing.JLabel opcion3JL;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
