/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.mycompany.proyecto_sistema_recomendaciones.Perro;
import javax.swing.JOptionPane;

/**
 *
 * @author viankacastro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGtamanio = new javax.swing.ButtonGroup();
        BGcolor = new javax.swing.ButtonGroup();
        BGPelo = new javax.swing.ButtonGroup();
        BGpersonalidad = new javax.swing.ButtonGroup();
        BGtoleranciaClima = new javax.swing.ButtonGroup();
        negroCB = new javax.swing.JCheckBox();
        pequenoCB = new javax.swing.JCheckBox();
        medianoCB = new javax.swing.JCheckBox();
        grandeCB = new javax.swing.JCheckBox();
        blancoCB = new javax.swing.JCheckBox();
        grisCB = new javax.swing.JCheckBox();
        multicolorCB = new javax.swing.JCheckBox();
        marronCB = new javax.swing.JCheckBox();
        cortoCB = new javax.swing.JCheckBox();
        largoCB = new javax.swing.JCheckBox();
        rizadoCB = new javax.swing.JCheckBox();
        sinPeloCB = new javax.swing.JCheckBox();
        activoEnergeticoCB = new javax.swing.JCheckBox();
        tranquiloRelajadoCB = new javax.swing.JCheckBox();
        sociableAmigableCB = new javax.swing.JCheckBox();
        indReservadoCB = new javax.swing.JCheckBox();
        calidosCB = new javax.swing.JCheckBox();
        friosCB = new javax.swing.JCheckBox();
        adaptableCB = new javax.swing.JCheckBox();
        Bbuscar = new java.awt.Button();
        fondoJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGcolor.add(negroCB);
        negroCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroCBActionPerformed(evt);
            }
        });
        getContentPane().add(negroCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        BGtamanio.add(pequenoCB);
        pequenoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pequenoCBActionPerformed(evt);
            }
        });
        getContentPane().add(pequenoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 20));

        BGtamanio.add(medianoCB);
        medianoCB.setFont(new java.awt.Font("Devanagari MT", 0, 24)); // NOI18N
        medianoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianoCBActionPerformed(evt);
            }
        });
        getContentPane().add(medianoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 20));

        BGtamanio.add(grandeCB);
        grandeCB.setFont(new java.awt.Font("Devanagari MT", 0, 24)); // NOI18N
        getContentPane().add(grandeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));

        BGcolor.add(blancoCB);
        blancoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancoCBActionPerformed(evt);
            }
        });
        getContentPane().add(blancoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        BGcolor.add(grisCB);
        getContentPane().add(grisCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        BGcolor.add(multicolorCB);
        getContentPane().add(multicolorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, -1, -1));

        BGcolor.add(marronCB);
        getContentPane().add(marronCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, -1, -1));

        BGPelo.add(cortoCB);
        getContentPane().add(cortoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        BGPelo.add(largoCB);
        getContentPane().add(largoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        BGPelo.add(rizadoCB);
        getContentPane().add(rizadoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        BGPelo.add(sinPeloCB);
        getContentPane().add(sinPeloCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        BGpersonalidad.add(activoEnergeticoCB);
        getContentPane().add(activoEnergeticoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        BGpersonalidad.add(tranquiloRelajadoCB);
        getContentPane().add(tranquiloRelajadoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        BGpersonalidad.add(sociableAmigableCB);
        getContentPane().add(sociableAmigableCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        BGpersonalidad.add(indReservadoCB);
        getContentPane().add(indReservadoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, -1, -1));

        BGtoleranciaClima.add(calidosCB);
        getContentPane().add(calidosCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        BGtoleranciaClima.add(friosCB);
        getContentPane().add(friosCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        BGtoleranciaClima.add(adaptableCB);
        getContentPane().add(adaptableCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, -1, -1));

        Bbuscar.setActionCommand("BUSCAR");
        Bbuscar.setBackground(new java.awt.Color(228, 176, 139));
        Bbuscar.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        Bbuscar.setForeground(new java.awt.Color(88, 45, 35));
        Bbuscar.setLabel("BUSCAR");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Bbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, 160, 50));

        fondoJL.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"/src/main/java/img/GRAFICA1.png")
        );
        getContentPane().add(fondoJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 1020, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pequenoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pequenoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pequenoCBActionPerformed

    private void medianoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medianoCBActionPerformed

    private void negroCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negroCBActionPerformed

    private void blancoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blancoCBActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
     String colorSeleccionado = "";
    String tamañoSeleccionado = "";
    String tipoPeloSeleccionado = "";
    String personalidadSeleccionada = "";
    String toleranciaClimaSeleccionada = "";
    
    // Obtener el color seleccionado
    if (negroCB.isSelected()) {
        colorSeleccionado = "Negro";
    } else if (blancoCB.isSelected()) {
        colorSeleccionado = "Blanco";
    } else if (grisCB.isSelected()) {
        colorSeleccionado = "Gris";
    } else if (multicolorCB.isSelected()) {
        colorSeleccionado = "Multicolor"; 
    } else if (marronCB.isSelected()) {
        colorSeleccionado = "Marron";
    }
    
    // Obtener el tamaño seleccionado
    if (pequenoCB.isSelected()) {
        tamañoSeleccionado = "Pequeño";
    } else if (medianoCB.isSelected()) {
        tamañoSeleccionado = "Mediano";
    } else if (grandeCB.isSelected()) {
        tamañoSeleccionado = "Grande";
    }
    
    if (cortoCB.isSelected()) {
        tipoPeloSeleccionado = "Corto";
    } else if (largoCB.isSelected()) {
        tipoPeloSeleccionado = "Largo";
    } else if (rizadoCB.isSelected()) {
        tipoPeloSeleccionado = "Rizado";
    }else if (sinPeloCB.isSelected()) {
        tipoPeloSeleccionado = "Sin Pelo ";
    }

    // Obtener la personalidad seleccionada
    if (activoEnergeticoCB.isSelected()) {
        personalidadSeleccionada = "Activo/Energetico";
    } else if (sociableAmigableCB.isSelected()) {
        personalidadSeleccionada = "Sociable/Amigable";
    } else if (tranquiloRelajadoCB.isSelected()) {
        personalidadSeleccionada = "Tranquilo/Relajado";
    }
      else if (indReservadoCB.isSelected()) {
        personalidadSeleccionada = "Independiente/Reservado";
    }

    // Obtener la tolerancia al clima seleccionada
    if (calidosCB.isSelected()) {
        toleranciaClimaSeleccionada = "Calidos";
    } else if (friosCB.isSelected()) {
        toleranciaClimaSeleccionada = "Frios";
    } else if (adaptableCB.isSelected()) {
        toleranciaClimaSeleccionada = "Baja";
    }

    
    // Continuar con la obtención de las otras características del perro de manera similar
    
    // Verificar si todas las características del perro fueron seleccionadas
    if (colorSeleccionado.isEmpty() || tamañoSeleccionado.isEmpty() || tipoPeloSeleccionado.isEmpty() || personalidadSeleccionada.isEmpty() || toleranciaClimaSeleccionada.isEmpty()) {
        // Mostrar un mensaje de error si alguna característica no fue seleccionada
        JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una opción en cada grupo.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Crear una instancia de la clase Perro utilizando los valores seleccionados
        Perro perro = new Perro(
            colorSeleccionado,
            tamañoSeleccionado,
            tipoPeloSeleccionado,
            personalidadSeleccionada,
            toleranciaClimaSeleccionada
        );
        
        // Hacer algo con el objeto Perro creado, como imprimirlo o guardarlo
        System.out.println("Se ha creado un nuevo perro con las siguientes características :D:");
        System.out.println(perro);
    }
    }//GEN-LAST:event_BbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGPelo;
    private javax.swing.ButtonGroup BGcolor;
    private javax.swing.ButtonGroup BGpersonalidad;
    private javax.swing.ButtonGroup BGtamanio;
    private javax.swing.ButtonGroup BGtoleranciaClima;
    private java.awt.Button Bbuscar;
    private javax.swing.JCheckBox activoEnergeticoCB;
    private javax.swing.JCheckBox adaptableCB;
    private javax.swing.JCheckBox blancoCB;
    private javax.swing.JCheckBox calidosCB;
    private javax.swing.JCheckBox cortoCB;
    private javax.swing.JLabel fondoJL;
    private javax.swing.JCheckBox friosCB;
    private javax.swing.JCheckBox grandeCB;
    private javax.swing.JCheckBox grisCB;
    private javax.swing.JCheckBox indReservadoCB;
    private javax.swing.JCheckBox largoCB;
    private javax.swing.JCheckBox marronCB;
    private javax.swing.JCheckBox medianoCB;
    private javax.swing.JCheckBox multicolorCB;
    private javax.swing.JCheckBox negroCB;
    private javax.swing.JCheckBox pequenoCB;
    private javax.swing.JCheckBox rizadoCB;
    private javax.swing.JCheckBox sinPeloCB;
    private javax.swing.JCheckBox sociableAmigableCB;
    private javax.swing.JCheckBox tranquiloRelajadoCB;
    // End of variables declaration//GEN-END:variables
}
